### ISSUE TITLE
Incorrect boundary in output GLB manifest

### ISSUE THREAD

**Issue by xeolabs** [Creoox/creoox-ifc2gltfcxconverter#6]
Seems there's a bug in `ifc2gltf`'s calculation of the `modelBoundsMax` and `modelBoundsMin` in the output GLB manifest.

Having converted the IFC for the Duplex IFC model into GLB, the manifest looks like this:

````json
{
    "inputFile": "/home/lindsay/xeolabs/xeokit-model-conversion-tests-feb12/inputFiles/ifc/Duplex/Duplex.ifc",
    "converterApplication": "ifc2gltfcxconverter",
    "converterApplicationVersion": "3.0.14",
    "conversionDate": "2024-02-29 22:15:56",
    "gltfOutFiles": [
        "convertedModels/ifc/projects/Duplex/models/Duplex/model.glb"
    ],
    "metadataOutFiles": [
        "convertedModels/ifc/projects/Duplex/models/Duplex/model.json"
    ],
    "numCreatedGltfMeshes": 857,
    "numCreatedMetaObjects": 246,
    "numExportedPropertySetsOrElementQuantities": 386,
    "modelBoundsMax": [
        17.491500000000002,
        4.382734000000028,
        9.0
    ],
    "modelBoundsMin": [
        -8.691499999999998,
        -22.182734,
        -1.5500000000000007
    ]
}
````

However, once the model is converted with `convert2xkt` to XKT and the XKT is loaded into xeokit's Viewer, the AABB
 is:

`[-0.24150000512599945, -1.550000011920929, -4.3827338218688965, 9.041500091552734, 6.634799883270084, 22.1827335357666]`

This AABB is the original boundary of the Duplex IFC model. 

I confirmed that by also loading the IFC model directly into xeokit's `Viewer`, using our `WebIFCLoaderPlugin`, where the AABB in the ````Viewer```` was also:

`[-0.24150002555848182, -1.55, -4.3827339109344585, 9.041500011920919, 6.634799883270084, 22.18273391093445]`.

**Comment by ifcapps** [comment]
There might be a problem with computing the bounding box of rotated geometric items, and these bboxes get unionized with parents bboxes.
I will check this.

**Comment by ifcapps** [comment]
I updated the current beta release with the exact approach. Turns out that it doesn't make a measurable difference in compute time.

**Comment by ifcapps** [comment]
The boundary compute method is fixed with version 3.0.21.

However there re is still one model that causes a similar issue:
The overall boundary is correct, but there are some objects that have coordinates of 7000000 or so, and a transform matrix above with -7000000 translation, which cancels out the large coordinate.
During conversion to gltf, the matrix remains intact, becauase it has double precision values, but not the meshes itself.
So some meshes end up having a wrong position.
I will try to implement a solution per-mesh + transform matrix, similar to the approach for the overall model.

**Comment by ifcapps** [comment]
You can imagine, that was hard to even figure out what was going on...

**Comment by ifcapps** [comment]
Solved meanwhile
